services:
  app:
    build: ./app
    deploy:
      replicas: 3

  mysql:
    build: ./mysql
    volumes:
      - todo-mysql-data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes: 
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app
      - mysql

volumes:
    todo-mysql-data:
