services:
  app:
    build: ./app
    deploy:
      replicas: 3
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}


  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes: 
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - app
      - mysql

volumes:
    mysql-data:
